### ISSUE TITLE
slf 18.6

### ISSUE THREAD

**Issue by raamuratto** [summertriangle-dev/more-ll-tools#1]
unit_type_m : will update 0 rows
unit_m : will update 3 rows
Traceback (most recent call last):
  File "decrypt_release_tag.py", line 83, in <module>
    plac.call(main)
  File "C:\Python34\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "C:\Python34\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(_(args + varargs + extraopts), *_kwargs)
  File "decrypt_release_tag.py", line 77, in main
    decrypt_rows(db, tablename)
  File "decrypt_release_tag.py", line 54, in decrypt_rows
    dec_values = decrypt_this(enc_values, keyid)
  File "decrypt_release_tag.py", line 25, in decrypt_this
    use = G_KEYBAG.get(str(keyid))["key"]
TypeError: 'NoneType' object is not subscriptable

**Comment by summertriangle-dev** [comment]
fixed? in fdcfce2
